### ISSUE TITLE
Error: Can't get TradingView symbol element on chart

### ISSUE THREAD

**Issue by suncity093-ui** [akumidv/tradingview-assistant-chrome-extension#319]
Error: Can't get TradingView symbol element on chart

**Comment by ludwigxaver** [comment]
seems its the top left of the screen they added a drop down and that is interfering with the bot capability to get the symbol

**Comment by suncity093-ui** [comment]
Thx 👍🏻

**Comment by suncity093-ui** [comment]
> [@smjhs990291](https://github.com/smjhs990291) [@kz4dor](https://github.com/kz4dor) [@suncity093-ui](https://github.com/suncity093-ui) How is it installed? Thanks.

 changing to this file tvChart.js

**Comment by suncity093-ui** [comment]
copy-paste)

**Comment by smjhs990291** [comment]
@kelvin874874 Did you reload the extension?

**Comment by kelvin874874** [comment]
> Did you reload the extension?

Yes, but appeared error

<img width="1153" height="599" alt="Image" src="https://github.com/user-attachments/assets/e8dacbed-1588-4939-ad68-109ff4ceca95" />

<img width="1176" height="429" alt="Image" src="https://github.com/user-attachments/assets/cf3cc31d-c19e-4f5c-9512-f3b8e4125216" />

**Comment by kz4dor** [comment]
Yo borre directamente el archivo de la carpeta y pegue el que compartio el compañero, guardar, recargar la extension y funciono

**Comment by mikeinvest** [comment]
This is how I fixed it:

1. Go here https://github.com/akumidv/tradingview-assistant-chrome-extension and click on "Code" and download it as ZIP
2. Unzip the file and replace the file tvChart.js in the appropriate folder
3. Load it on your browser in developer mode.
4. Important reload the tradingview page and it works.
5.

**Comment by jiangyoutan** [comment]
All guys above please refer to issue #310 where the script was updated  by A1exZl  and is working well.

**Comment by kelvin874874** [comment]
Thank you so much for the information. It's already working. I've put the link below.

https://github.com/user-attachments/files/24346695/tradingview-assistant-chrome-extension-main.zip

**Comment by Fade-image** [comment]
To qwert76ya, 
Thanks for your reply! But I do not understand "step 3. Load it on your browser in developer mode".  I use Chrome, but I do not know how to open "it" in "developer mode" in Chrome.  Can you explain it in more detail? What does "it" means? How to open "it" in "developer mode" ?

**Comment by arullr001** [comment]
> > This is how I fixed it:
> > 
> > 1. Go here https://github.com/akumidv/tradingview-assistant-chrome-extension and click on "Code" and download it as ZIP
> > 2. Unzip the file and replace the file tvChart.js in the appropriate folder
> > 3. Load it on your browser in developer mode.
> > 4. Important reload the tradingview page and it works.
> 
> Everything is great, everything works



> To mikeinvest ,jiangyoutan and kelvin874874,
> 
> I have tried your method, but I still got error message shown below. Can anyone hel me to solve this problem?
> 
> <img alt="Image" width="1009" height="213" src="https://private-user-images.githubusercontent.com/186440902/530866197-58d4127a-0851-45f5-83ec-1aa7e1ab4191.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjczMTE2NDIsIm5iZiI6MTc2NzMxMTM0MiwicGF0aCI6Ii8xODY0NDA5MDIvNTMwODY2MTk3LTU4ZDQxMjdhLTA4NTEtNDVmNS04M2VjLTFhYTdlMWFiNDE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEwMVQyMzQ5MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWUyZDE0NTdiOWNlYzZhYWVmNGU4ZjBmYmRlZTM4MjQ0NDAyNjgzZmExY2I0YTVkNjRkYjc4NjJiNjk3ZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UrvDLyjwivxapV9pSV6CC40jaczmMmR6EphBP4RLZt8">

Same here. Followed the steps. Loaded the extension by enabling the developer mode in the Chrome as well as Comet. The error remains.

**Comment by akumidv** [comment]
New version v2.11.23 with fixes for new TV UI changes committed to repository and has been sent to WebStore review and publish
