### ISSUE TITLE
Error on test strategy

### ISSUE THREAD

**Issue by sadeqhatami** [akumidv/tradingview-assistant-chrome-extension#57]
hi
i can't run test strategy.
when i try to test strategy i get this error.

![image](https://user-images.githubusercontent.com/12267341/185357729-56efece4-7251-4e6d-9896-16ed6d886205.png)

Version
1.14

An error has occurred.
Reload the page and try again.
You can describe the problem by following 
Error message: Tradingview UI changed. Can't get performance headers. Please contact support

**Comment by chaiyapruekr** [comment]
same problem

**Comment by dannydanny77** [comment]
Same error here... It was running this morning. When I refreshed the page, stopped working with the same UI change error...

**Comment by stefantabakovq** [comment]
OMFG they keep updating

**Comment by stefantabakovq** [comment]
Replace old with:
**strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.backtesting-content-wrapper.widgetContainer-Ywsi3NS8 > div > div > div > div > table > thead > tr > th',
strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.backtesting-content-wrapper.widgetContainer-Ywsi3NS8 > div > div > div > div > table > tbody > tr',**

**Comment by stefantabakovq** [comment]
And re-install, refresh page! 
maybe **div.backtesting-content-wrapper.widgetContainer-Ywsi3NS8** should be **div[class^="content-wrapper.widgetContainer"]** in order to work in future but I don't have time to test

**Comment by dannydanny77** [comment]
I tried both, replacing strategyReportHeader: and strategyReportRow: as suggested, uninstalled, reinstalled and refreshed TW page on Chrome, but unfortunately doesn't work for me.

**Comment by stefantabakovq** [comment]
> I tried both, replacing strategyReportHeader: and strategyReportRow: as suggested, uninstalled, reinstalled and refreshed TW page on Chrome, but unfortunately doesn't work for me.

It appears that unfortunately path may be different for different TV accounts. Inspect element and follow general path I wrote above to find this performance table, right click on it and say Copy > Selector. Then paste in the js file and try again. Tradingview will keep updating UI and sadly fastest way to fix would be to learn to update yourself :/

**Comment by dannydanny77** [comment]
> > I tried both, replacing strategyReportHeader: and strategyReportRow: as suggested, uninstalled, reinstalled and refreshed TW page on Chrome, but unfortunately doesn't work for me.
> 
> It appears that unfortunately path may be different for different TV accounts. Inspect element and follow general path I wrote above to find this performance table, right click on it and say Copy > Selector. Then paste in the js file and try again. Tradingview will keep updating UI and sadly fastest way to fix would be to learn to update yourself :/

Did exactly as you wrote... And it worked... Thank you very much for the instructions, really appreciate it.

**Comment by stefantabakovq** [comment]
@iceman4828 https://github.com/akumidv/tradingview-assistant-chrome-extension/issues/58

**Comment by beskrovnykh** [comment]
same problem

**Comment by stefantabakovq** [comment]
> same problem

#58

**Comment by MrDenfish** [comment]
Thanks for the remedy to this problem. I have the same headers / body of performance table error, made the corrections suggested, reloaded, refreshed however, the error persists. I'll give it another try...

**Comment by akumidv** [comment]
I guess today this error is fixed. But I checked only on my pro+ account and do not know how it will work under premium subscription type. I sent changes to review to google chrome as version 1.15. This version is also available as usual from repository.

**Comment by duocyber** [comment]
Since version 1.12 to the newly version 1.15 on chrome, I always got the 'There is not strategy name element on page' and it may look different from others.  I try every re-install, refresh or patch; it still not work out. (the F12 console not immediate error but a 30 sec later with 'Value is null'
![TV assistant err 220819](https://user-images.githubusercontent.com/6591215/185606420-ba17c064-3ba9-42bd-94a9-2f56c922a50e.png)
)

**Comment by duocyber** [comment]
It's now ok for me now for v1.15.  I have changed the selector UI element of strategyCaption: to '#bottom-area div[class^="backtesting"]  [class^="strategyGroup"]  [class^="content"]'.

**Comment by duocyber** [comment]
Found to have some strategy pages got different CSS elements structure even on same web browser.  Maybe I need to clean browsing data, which I'd not like to do it now. So the solution is to use both **'div[data-qa-strategy-title]'** and **'[class^="content"]'** in the same UI selector which it works.<br/><br/>Then it would be: <br/>   strategyCaption: '#bottom-area div[class^="backtesting"]  [class^="strategyGroup"]  **[class^="content"],div[data-qa-strategy-title]'**,

**Comment by Quantbrinx** [comment]
Is anyone still having the same problem even after updating to the new version 1.15? I've done everything specified and more and I'm still having the same issues. 
![image](https://user-images.githubusercontent.com/89876171/186465447-eb36fe66-e588-49f7-8581-1de5fd4150fe.png)

**Comment by stefantabakovq** [comment]
> Is anyone still having the same problem even after updating to the new version 1.15? I've done everything specified and more and I'm still having the same issues. 
> ![image](https://user-images.githubusercontent.com/89876171/186465447-eb36fe66-e588-49f7-8581-1de5fd4150fe.png)
> 

I assume you have added the new update straight from google extension store? I just tried fresh install from there and works fine..

**Comment by Quantbrinx** [comment]
yes, I installed it straight from the extension store. However, I haven't edited anything for this version 1.15 and trying it as it is.

**Comment by MrDenfish** [comment]
try to reinstall manually...https://github.com/akumidv/tradingview-assistant-chrome-extension scroll down to Setup.
V1.15 is working great.

**Comment by Quantbrinx** [comment]
I tried to install it manually and again from the extension and it's still not working. To clarify, do I still have to make the changes mentioned above for 1.15? or that was for 1.14. I haven't made any changes to 1.15 yet, so wondering if that might be the reason.

**Comment by stefantabakovq** [comment]
> I tried to install it manually and again from the extension and it's still not working. To clarify, do I still have to make the changes mentioned above for 1.15? or that was for 1.14. I haven't made any changes to 1.15 yet, so wondering if that might be the reason.

No, these changes were a temporary fix, the uploaded version should be good to go after install without making any changes to it, from chrome store or manually... Which makes this issue very weird. What type of tradingview account do you have? Can you try maybe installing on another device to see if it's from the browser? 

Maybe clear browser cache and try fresh install? I'm shooting in the dark though...

**Comment by Quantbrinx** [comment]
Finally figured it out. Thanks

**Comment by Quantbrinx** [comment]
Finally figured it out. Thanks

**Comment by Quantbrinx** [comment]
Finally figured it out. Thanks

**Comment by Quantbrinx** [comment]
Finally figured it out. Thanks

**Comment by Quantbrinx** [comment]
Finally figured it out. Thanks
