### ISSUE TITLE
New version (2.1 / 2.0) is very slow

### ISSUE THREAD

**Issue by t563t** [akumidv/tradingview-assistant-chrome-extension#80]
Hi and thank you for this utility - it is awesome.

But with latest version ther is significantly slower (2-3x slower). Is there any solution how to speed it up? - To be fast like before... 

Thanks a lot.

PT

**Comment by akumidv** [comment]
Do you set delay time in options?

**Comment by akumidv** [comment]
I found the problem. Fixed in current version.

**Comment by t563t** [comment]
I tried changing the time settings, but it has no effect. At the moment the performance summary is loaded the assistant waits between 5-10 seconds each time. In previous versions it was much faster. I tested it on two pc's, cleared the cache (assistant, chrome), it's still the same :-(

**Comment by t563t** [comment]
ok, sorry, i missed your last mail. Im going to test it… :-)

**Comment by t563t** [comment]
Resolved - thank you very much. I really appreciate your work!!!

PT
